package com.icareyou.food;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.icareyou.food.Reports;

import com.icareyou.food.ReportsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig reportsDaoConfig;

    private final ReportsDao reportsDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        reportsDaoConfig = daoConfigMap.get(ReportsDao.class).clone();
        reportsDaoConfig.initIdentityScope(type);

        reportsDao = new ReportsDao(reportsDaoConfig, this);

        registerDao(Reports.class, reportsDao);
    }
    
    public void clear() {
        reportsDaoConfig.getIdentityScope().clear();
    }

    public ReportsDao getReportsDao() {
        return reportsDao;
    }

}
