package com.icareyou.food;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table REPORTS.
 */
public class Reports {

    private Long id;
    /** Not-null value. */
    private String reportcat;
    private String reportid;
    private String batchno;
    private String companyname;
    private String companycountry;
    private String productname;
    private String importexport;
    private String guarantee;
    private String result;
    private Boolean watched;
    private java.util.Date created_at;
    private java.util.Date udpated_at;

    public Reports() {
    }

    public Reports(Long id) {
        this.id = id;
    }

    public Reports(Long id, String reportcat, String reportid, String batchno, String companyname, String companycountry, String productname, String importexport, String guarantee, String result, Boolean watched, java.util.Date created_at, java.util.Date udpated_at) {
        this.id = id;
        this.reportcat = reportcat;
        this.reportid = reportid;
        this.batchno = batchno;
        this.companyname = companyname;
        this.companycountry = companycountry;
        this.productname = productname;
        this.importexport = importexport;
        this.guarantee = guarantee;
        this.result = result;
        this.watched = watched;
        this.created_at = created_at;
        this.udpated_at = udpated_at;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getReportcat() {
        return reportcat;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setReportcat(String reportcat) {
        this.reportcat = reportcat;
    }

    public String getReportid() {
        return reportid;
    }

    public void setReportid(String reportid) {
        this.reportid = reportid;
    }

    public String getBatchno() {
        return batchno;
    }

    public void setBatchno(String batchno) {
        this.batchno = batchno;
    }

    public String getCompanyname() {
        return companyname;
    }

    public void setCompanyname(String companyname) {
        this.companyname = companyname;
    }

    public String getCompanycountry() {
        return companycountry;
    }

    public void setCompanycountry(String companycountry) {
        this.companycountry = companycountry;
    }

    public String getProductname() {
        return productname;
    }

    public void setProductname(String productname) {
        this.productname = productname;
    }

    public String getImportexport() {
        return importexport;
    }

    public void setImportexport(String importexport) {
        this.importexport = importexport;
    }

    public String getGuarantee() {
        return guarantee;
    }

    public void setGuarantee(String guarantee) {
        this.guarantee = guarantee;
    }

    public String getResult() {
        return result;
    }

    public void setResult(String result) {
        this.result = result;
    }

    public Boolean getWatched() {
        return watched;
    }

    public void setWatched(Boolean watched) {
        this.watched = watched;
    }

    public java.util.Date getCreated_at() {
        return created_at;
    }

    public void setCreated_at(java.util.Date created_at) {
        this.created_at = created_at;
    }

    public java.util.Date getUdpated_at() {
        return udpated_at;
    }

    public void setUdpated_at(java.util.Date udpated_at) {
        this.udpated_at = udpated_at;
    }

}
